name: "Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up GO 1.20.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
